### PR TITLE
Updated readme with install instructions

### PR DESCRIPTION
**Pull request by remiks**
Added some more install instructions. Make sense?

Signed-off-by: remi.vandemir <remi.vandemir@amesto.no>

### CODE REVIEW

**Comment by daiyanze** [comment]
I think a repo contributor would like to use it this way. Usually, a user can start the development from a barebone repo by adding up minimum packages. If we recommend users downloading the repo, they'll also receive "devDependencies" packages after installation.

**Comment by remiks** [comment]
aha. I understand. What im trying to figure out is how to do an upgrade with the changes you`re doing to the theme in an easy manner.. Right now it`s a bit confusing.. Any ideas?

**Comment by daiyanze** [comment]
I see... You meant to have a doc for our repo contributors? I think for the end users, they just need to install the package instead of downloading the whole repo.

Even with the earlier issue of the upgrade you encountered, the published npm package itself won't put those users who started from an empty repo into the situation similar to yours. (The upgrade manual is located in the release page https://github.com/Pitayan/gatsby-theme-pitayan/releases/tag/v0.5.0)

**Comment by remiks** [comment]
Sure, we can use the description I made for contributors and not end users. 

BUT. I`am really struggling to do an upgrade in our repo. You`re welcome to do a fork and try: https://github.com/amestofortytwo/blog

**Comment by remiks** [comment]
Seems like I got it to build now here: https://github.com/remiks/amestofortywo-blog/tree/update-to-theme-v0.5.0

**Pull request closed without merging**
